name: activity_challenge
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.1.7
  flutter_web_auth: ^0.5.0
  go_router: ^14.2.0
  desktop_drop: ^0.5.0
  shared_preferences: ^2.3.5
  csv: ^6.0.0
  intl: ^0.18.0
  file_picker: ^5.0.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
