name: Treenix
description: "Track you movement!"
publish_to: "none"
version: 0.1.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.1.7
  flutter_web_auth: ^0.5.0
  go_router: ^14.2.0
  shared_preferences: ^2.3.5
  csv: ^6.0.0
  intl: ^0.19.0
  # file_picker: ^5.0.0
  mapbox_gl: ^0.16.0
  polyline_codec: ^0.1.6
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  fl_chart: ^0.63.0
  flutter_web_plugins:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
