List<Map<String, dynamic>> apireturn = [
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Evening Swim",
    "distance": 76.4,
    "moving_time": 74,
    "elapsed_time": 74,
    "total_elevation_gain": 0.0,
    "type": "Swim",
    "sport_type": "Swim",
    "id": 13248046291,
    "start_date": "2025-01-02T17:11:06Z",
    "start_date_local": "2025-01-02T19:11:06Z",
    "timezone": "(GMT+02:00) Europe/Tallinn",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 2,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a13248046291",
      "summary_polyline": "}t}iJmeovC?p@L}A?ZCDII",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [59.47, 24.82],
    "end_latlng": [59.47, 24.82],
    "average_speed": 1.032,
    "max_speed": 1.62,
    "average_cadence": 38.2,
    "average_temp": 8,
    "has_heartrate": true,
    "average_heartrate": 124.0,
    "max_heartrate": 141.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 5.0,
    "elev_low": 5.0,
    "upload_id": 14129175496,
    "upload_id_str": "14129175496",
    "external_id": "garmin_ping_398808002573",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Afternoon Nordic Ski",
    "distance": 11849.1,
    "moving_time": 4220,
    "elapsed_time": 6200,
    "total_elevation_gain": 130.0,
    "type": "NordicSki",
    "sport_type": "NordicSki",
    "id": 13255685469,
    "start_date": "2025-01-03T13:27:07Z",
    "start_date_local": "2025-01-03T15:27:07Z",
    "timezone": "(GMT+02:00) Europe/Tallinn",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 8,
    "kudos_count": 7,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a13255685469",
      "summary_polyline":
          "{}h_JkyadDSTcARM\\UdBGfAe@pEe@hGJb@Dj@@vACx@RzA\\f@hBIpC?dAPl@bAZnBBbA?xCDdAD^NTXJn@B~@m@XAj@t@`AzBPj@Jj@Nb@?HPd@j@p@ZTzBb@f@GTSBQe@_AOw@Q_@Q{AI}AEoBOk@Cg@Kc@?g@McAk@_CUs@_@g@q@EWKUS[s@Sq@m@cCe@cDEmA@oAAaCSWa@EUSQaAOgCESS]g@_@aBw@a@[o@WcAfBSAg@JM^I`@_@fDKj@e@~EStCAd@Jj@Bv@CvAJzATp@ZTnDMzA@PFRe@ZkBf@gCn@_Fh@sCF}@]aDIqAQq@UU}Ak@_Ao@i@Sc@TSp@MRs@IMDM\\]bCs@rGc@dGSzFMp@e@lAaAjBqAxASl@KjA[jHId@GtBIfAg@xBI~@Bl@T|@AhJ\\dH?|CEtCDbEb@bIA~BMfBOrAUnDAnC?}CV}ETiCByBGkCUkDKgCHkJYmGAoAD_GG}@SoA?o@Fg@d@mBDa@PuDNcAN{AJ{EFi@Zw@~@gA|AcDRkAVsEJDHt@ChCRrAXf@`@JjAOhCJl@KRa@Pm@|@sEHy@pAsHBeAm@kFQi@a@U{Ai@q@_@u@QG?ONYp@UNe@GYRc@pD_@fCi@pGCzAHxACzBJfANl@LTPLRB|B_@bAJt@ATIHKTy@dByJTwBJa@RuA]gDG{AQm@SQi@MqBgAo@Oa@D_@dAyAj@eAdIg@tGAj@JfA?tDXvAFJTJhCIlBFb@E\\g@Rw@r@}Dd@sDx@aFCm@QkAYoC[s@cDaBo@QOBWXa@t@_@?e@PMj@eAxIWlDCx@?|@FrACvBNpAHZRXb@H`GIXYPm@x@kE`B}L]_CQaBIe@IS]YiD{Ae@@ONYl@OLu@FSd@uAnLSnCAn@HnBAvABr@RpATb@^J~CSfAJl@OVm@b@yBr@uEl@qETsAEy@k@wEWe@eBq@kAo@s@OOPYlAq@Wa@FEFKj@m@vFs@fIAhAH`AGrBFz@Pr@JRXXdBCfCLLC`@Dd@Xj@rAThAB`@Pv@EbCNbBLTHLf@Hd@MXSPC^HLJpAbCdAfDh@p@BPHBXVtB^b@ARIHSM}@mAqDG{@G_DKsA]aCs@_D_@y@UQ{Au@Yk@yAwEQoBGoCBeCE[S_@c@IQOGSQeAO}BQe@kDkBo@K]XQ\\",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [57.72, 27.05],
    "end_latlng": [57.72, 27.05],
    "average_speed": 2.808,
    "max_speed": 8.383,
    "average_temp": 9,
    "has_heartrate": true,
    "average_heartrate": 167.4,
    "max_heartrate": 200.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 262.8,
    "elev_low": 237.8,
    "upload_id": 14137389298,
    "upload_id_str": "14137389298",
    "external_id": "garmin_ping_399087245914",
    "from_accepted_tag": false,
    "pr_count": 3,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Night Swim",
    "distance": 44.4,
    "moving_time": 96,
    "elapsed_time": 96,
    "total_elevation_gain": 0.0,
    "type": "Swim",
    "sport_type": "Swim",
    "id": 13257689393,
    "start_date": "2025-01-03T19:34:57Z",
    "start_date_local": "2025-01-03T21:34:57Z",
    "timezone": "(GMT+02:00) Europe/Tallinn",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 3,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a13257689393",
      "summary_polyline": "}_f_JsscdDQs@FC?@?CADBI",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [57.71, 27.06],
    "end_latlng": [57.71, 27.06],
    "average_speed": 0.462,
    "max_speed": 1.62,
    "average_temp": 15,
    "has_heartrate": true,
    "average_heartrate": 103.1,
    "max_heartrate": 107.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 265.6,
    "elev_low": 265.0,
    "upload_id": 14139542847,
    "upload_id_str": "14139542847",
    "external_id": "garmin_ping_399149041730",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Night Swim",
    "distance": 38.7,
    "moving_time": 107,
    "elapsed_time": 107,
    "total_elevation_gain": 0.0,
    "type": "Swim",
    "sport_type": "Swim",
    "id": 13257917536,
    "start_date": "2025-01-03T19:55:03Z",
    "start_date_local": "2025-01-03T21:55:03Z",
    "timezone": "(GMT+02:00) Europe/Tallinn",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 4,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a13257917536",
      "summary_polyline": "e`f_JotcdDEc@@R",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [57.71, 27.06],
    "end_latlng": [57.71, 27.06],
    "average_speed": 0.362,
    "max_speed": 1.62,
    "average_temp": 14,
    "has_heartrate": true,
    "average_heartrate": 132.3,
    "max_heartrate": 149.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 265.4,
    "elev_low": 265.1,
    "upload_id": 14139756190,
    "upload_id_str": "14139756190",
    "external_id": "garmin_ping_399155139195",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Night Swim",
    "distance": 32.1,
    "moving_time": 82,
    "elapsed_time": 82,
    "total_elevation_gain": 0.0,
    "type": "Swim",
    "sport_type": "Swim",
    "id": 13258472356,
    "start_date": "2025-01-03T21:20:13Z",
    "start_date_local": "2025-01-03T23:20:13Z",
    "timezone": "(GMT+02:00) Europe/Tallinn",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 2,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a13258472356",
      "summary_polyline": "e`f_JctcdD?WG??A",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [57.71, 27.06],
    "end_latlng": [57.71, 27.06],
    "average_speed": 0.391,
    "max_speed": 1.62,
    "average_temp": 22,
    "has_heartrate": true,
    "average_heartrate": 141.8,
    "max_heartrate": 157.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 265.4,
    "elev_low": 265.1,
    "upload_id": 14140343171,
    "upload_id_str": "14140343171",
    "external_id": "garmin_ping_399175134791",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Afternoon Nordic Ski",
    "distance": 20074.2,
    "moving_time": 5977,
    "elapsed_time": 10155,
    "total_elevation_gain": 164.0,
    "type": "NordicSki",
    "sport_type": "NordicSki",
    "id": 13264079105,
    "start_date": "2025-01-04T11:11:31Z",
    "start_date_local": "2025-01-04T13:11:31Z",
    "timezone": "(GMT+02:00) Europe/Tallinn",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 4,
    "kudos_count": 6,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a13264079105",
      "summary_polyline":
          "w}h_JqyadDS[Av@g@@_@^wAhK[nFHxBGxBHdAd@pArA[zEDvAgHzA{Km@yE_@cAgE{By@f@t@VtDvBh@LLYMo@cEqBa@G]l@Vn@rEbBb@MIu@oEyBc@@O^@f@NH|EjBX?FWKq@qEyBe@HIzAjF~A\\WEg@UYmDeB{@@?vAlEtAn@?FYMg@sDiBs@ISTFjAfF|A^QWy@oEwBa@P@lAx@BfDxA`@UOo@yDgBw@AEr@HZbF`BVQA_@Y]sDeBk@DElAnATs@UFIb@h@DKy@SjA`@{A]AQJDUM[cB\\r@Fx@ITmB@u@dFw@jJ@rH^nBt@VzAQlDd@Xs@X`Aa@[]p@aFp\\NdWNfG?rJ_@}WBoQlFy^zBaMr@}Gk@iF[{@iEqB]H]v@}@H_@b@sArK[jEEr@JzEh@tBd@VrGGXi@h@uCpB_Nm@qGYeA{EmBy@dAcAR{@pFq@|FMlDJbB?fDZtA`@PjGAf@_@pAwHlA{Jo@qFMk@i@_@_E{Am@jAwA`@yAzLWtEDnEP`BZv@d@NjEArAa@|CcSBsAm@{Ei@aAyDaB]Fu@lA]Ei@l@oAdK[lELvHTdA\\b@nDDdCc@fBaKr@_Hg@eGOc@m@i@wDuAs@hAoAd@u@tE_AnLL`G^`BtGDl@QZ}@lCiQ@}@y@aGY_@{DiB_@Fm@fAy@J[x@c@bDw@|IEjBFvETbBP\\vGJ`@KTm@rCmRCoAg@wEc@w@sDcBk@Eq@pA{@PSb@uA|MMxCHhFd@~BvH@Zs@f@sCbAeJf@}BQiC_@mDoDyBw@KcArAaARaAtFy@hJJdI\\pA\\XjGCp@{@r@cE~AcLDy@i@{EYaAqE{BuAvAaAT[rBa@zCm@pILxIVv@^RhGB\\STm@nCgRe@yGUy@YUmEmBw@zAu@FQVwAlLYfFJlFTvAj@f@tGKZo@l@yClB{MA}@s@gFWm@gCiAaBMm@`AeANo@nEg@hEW~ELnHLx@f@j@tCYbCNhAeEpBmNk@mGWw@SQmD_Bg@@{@rA]Ac@^kAxI[|E?zITz@Xb@x@DxEEf@_@jByJ~@yGi@yFWaAaDcBoAOq@`AcAXQr@mAjKUtDPdITv@XThGDb@]Rk@f@{CnBeNi@aGc@y@sDcBe@Am@vAR}A",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [57.72, 27.05],
    "end_latlng": [57.72, 27.05],
    "average_speed": 3.359,
    "max_speed": 9.65,
    "average_temp": 9,
    "has_heartrate": true,
    "average_heartrate": 170.6,
    "max_heartrate": 190.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 257.4,
    "elev_low": 239.2,
    "upload_id": 14146375204,
    "upload_id_str": "14146375204",
    "external_id": "garmin_ping_399371594651",
    "from_accepted_tag": false,
    "pr_count": 2,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Evening Nordic Ski",
    "distance": 5142.5,
    "moving_time": 1981,
    "elapsed_time": 3165,
    "total_elevation_gain": 30.0,
    "type": "NordicSki",
    "sport_type": "NordicSki",
    "id": 13266114710,
    "start_date": "2025-01-04T16:33:33Z",
    "start_date_local": "2025-01-04T18:33:33Z",
    "timezone": "(GMT+02:00) Europe/Tallinn",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 5,
    "comment_count": 0,
    "athlete_count": 3,
    "photo_count": 0,
    "map": {
      "id": "a13266114710",
      "summary_polyline":
          "c~h_J}xadDQHm@BKLGJu@pGU|Ac@fFAf@HrAB`AEpABZNjAZn@RFTAt@Gn@KR@BBh@Cn@@d@CNKJY\\}BXyCl@{C\\yBReA@m@[_CQiBW_AWS]QyCiAM?ILEn@Nf@TJt@RzA\\d@R\\IHe@O_@mAc@IAMEa@QcAm@WAM\\A`@@RHV^JPLZJl@NtAd@ZCLWKc@UQ[I_@S]MsAq@[GI@KLAX@RZb@h@RhAZfA^PFHCHU?WIUUOs@WoAu@i@Ui@BKXDbAt@PDECIWE@G@?RZBCEIUBCAAKDEB?JVBA?E]CK[LTP@DLEFCAS]CB?Hd@B@NABYYCHF@`@A@JEHC?[e@GAEHDF^GF@BB?FCBa@[C?GD?BFHXGPHCHA?IEMQOMAJJLXDNCF@@HCBEKEBHCAHCAEIAD@@LGDFABEBIQCH@BBCCKODAEDM@HADKICF@?BEACECKBCG@EDA@J?BE@BM@B@HCBCE@GBBE@BKBBAJEDBEX?NNHAJDJFTDPLPDZRr@LBCFMAa@QY}Ae@YWa@Se@Og@?G\\Bl@_@?o@IKDURCJMl@cA~IYtDArAL`BCxA@`@Dn@R`AJNXH`@?d@U`A@NAZJNBTCd@B\\OLi@XuBJe@LgARiAXeCn@mE@c@O{@SiDQq@[YWK[G{@g@iAc@M@KDOTIZW`@WA[DMNENM|@{@zGa@zEAh@An@HdACdBBlATjAFPLJLBP@f@GNG\\EjCJ`@CTQFm@l@mDHi@?y@FWVcBJcAn@_DAu@M_A[sDGQYWg@S}Ay@i@Si@?W~@IPEBc@FWZOv@EnANf@DBNGRe@TwBZyA",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [57.72, 27.05],
    "end_latlng": [57.72, 27.05],
    "average_speed": 2.596,
    "max_speed": 6.357,
    "average_temp": 9,
    "has_heartrate": true,
    "average_heartrate": 163.2,
    "max_heartrate": 184.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 256.2,
    "elev_low": 244.6,
    "upload_id": 14148563904,
    "upload_id_str": "14148563904",
    "external_id": "garmin_ping_399422087396",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Lunch Hike",
    "distance": 11777.5,
    "moving_time": 11194,
    "elapsed_time": 14747,
    "total_elevation_gain": 400.0,
    "type": "Hike",
    "sport_type": "Hike",
    "id": 13272588984,
    "start_date": "2025-01-05T09:16:36Z",
    "start_date_local": "2025-01-05T11:16:36Z",
    "timezone": "(GMT+02:00) Europe/Tallinn",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 7,
    "comment_count": 0,
    "athlete_count": 3,
    "photo_count": 0,
    "map": {
      "id": "a13272588984",
      "summary_polyline":
          "{~e_JgcddDp@UjA_AV\\V`C^vBNXbD^bAb@dFx@t@`@vBQbJnFZb@fCnBnB`B~A~Ar@c@vCnBXDn@o@b@CJ{@j@gAHqCTi@GqEg@gBKq@?w@ZyBZaAP{Al@oBDo@o@_Ba@cCj@qCg@{ASsEo@aCC_AVuCcA_A{Au@He@HENaC^mA?[FSZ?|Bb@x@\\z@GrAt@v@SF[z@Ad@i@Jg@b@k@bADz@n@T\\xHo@DcB?kDNoCMm@TgBh@O]`@WrALp@Kj@AjGKtA?vBQtB@fArB|F~@lDVBXh@^NfAOd@N\\lA?bAXdCWlAa@vAGnAMPkAHYXm@CMrBx@r@~CjAn@xA|@n@bAdEXnCf@bC^`E@`AqAdBYvANvBlAbHU~Aa@|AIbC?`@d@`CEtAS`B}@xDaAL]^kAjHu@fCUh@e@a@{@tB_@^gCDMk@SMM|@i@h@c@jAe@?g@b@yB{@{ELqATk@f@u@T}@IwA_AuDiAc@sBIaAGOIBSk@[nAg@HkAa@[]aCuNa@u@m@e@kBPs@f@cBrB_@v@[pAkBpCiFLiAn@IVaACmAq@Gs@MSaA@eA`B]dB[l@o@n@q@Ae@cA_@MaAqAa@TFMc@MCSBiAYo@[gBAaCk@_B@mBHi@K}An@}AQkA{@u@u@uAWu@{@iFq@oBoAs@m@qAAk@SDa@q@i@CU_@Yz@YlAw@fAk@?c@i@UXkCDuCl@WMgCl@{@j@]bAM?e@hAa@PKXFa@VKn@_BPyAJwDTm@p@e@PcAARQ@n@YEaDs@_IEaFQuAEwB@UjAo@LkCQ[[EGi@N{@d@g@\\aB|@kB^]D_BNg@`Bc@tBsAj@?\\oALHN[n@Fp@~@l@EPvAXLd@x@Fz@VbB`@z@n@mBHcDRgAKSE}AaAy@Se@E}@k@gA]KK_AQCST}AcAiBA_AH{EvD_Au@g@Ai@wAKgDUaA@cA_@uAUSAYPiAK}BRiAYcCH[Sw@Nu@?w@Wm@@_ASuAo@uB^q@To@Hs@XGDYLCTcAp@_@Vy@`@c@zBiA`@TVw@TDdAq@TDfAvD@^Ir@i@j@c@zAGdB~AvB`@BP~@NCd@t@b@bB@`DMt@f@z@",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [57.71, 27.06],
    "end_latlng": [57.71, 27.07],
    "average_speed": 1.052,
    "max_speed": 2.5,
    "average_cadence": 54.2,
    "average_temp": 10,
    "has_heartrate": true,
    "average_heartrate": 123.9,
    "max_heartrate": 158.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 318.8,
    "elev_low": 246.2,
    "upload_id": 14155563041,
    "upload_id_str": "14155563041",
    "external_id": "garmin_ping_399649665461",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Night Workout",
    "distance": 0.0,
    "moving_time": 3971,
    "elapsed_time": 3971,
    "total_elevation_gain": 0,
    "type": "Workout",
    "sport_type": "Workout",
    "id": 13284243623,
    "start_date": "2025-01-06T19:13:24Z",
    "start_date_local": "2025-01-06T21:13:24Z",
    "timezone": "(GMT+02:00) Africa/Blantyre",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 1,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {"id": "a13284243623", "summary_polyline": "", "resource_state": 2},
    "trainer": true,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [],
    "end_latlng": [],
    "average_speed": 0.0,
    "max_speed": 0.0,
    "average_temp": 20,
    "has_heartrate": true,
    "average_heartrate": 113.6,
    "max_heartrate": 134.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 0.0,
    "elev_low": 0.0,
    "upload_id": 14168135613,
    "upload_id_str": "14168135613",
    "external_id": "garmin_ping_400048940896",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Morning Swim",
    "distance": 4300.0,
    "moving_time": 4006,
    "elapsed_time": 4299,
    "total_elevation_gain": 0,
    "type": "Swim",
    "sport_type": "Swim",
    "id": 13296706285,
    "start_date": "2025-01-08T05:47:49Z",
    "start_date_local": "2025-01-08T07:47:49Z",
    "timezone": "(GMT+02:00) Africa/Blantyre",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 7,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {"id": "a13296706285", "summary_polyline": "", "resource_state": 2},
    "trainer": true,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [],
    "end_latlng": [],
    "average_speed": 1.073,
    "max_speed": 3.58,
    "has_heartrate": true,
    "average_heartrate": 147.0,
    "max_heartrate": 185.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 0.0,
    "elev_low": 0.0,
    "upload_id": 14181471069,
    "upload_id_str": "14181471069",
    "external_id": "garmin_ping_400481236157",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Evening Nordic Ski",
    "distance": 7578.7,
    "moving_time": 2544,
    "elapsed_time": 3082,
    "total_elevation_gain": 27.0,
    "type": "NordicSki",
    "sport_type": "NordicSki",
    "id": 13310421574,
    "start_date": "2025-01-09T18:22:25Z",
    "start_date_local": "2025-01-09T20:22:25Z",
    "timezone": "(GMT+02:00) Europe/Tallinn",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 15,
    "kudos_count": 7,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a13310421574",
      "summary_polyline":
          "_nniJ{{luCj@tC^r@RJb@Oh@DJD^^h@`BHJDK@o@Ak@BmCEuBDaDDuA?mBMiA_@oAIc@OMSa@SwAMyAEiAYaBe@yEHgDBIPQ@o@KyA?_AC[Mq@WeCE_AGcCQ_AIq@A}B@_AK}CA}B?o@FoAJWDALNDXRhBPzBEt@Of@SPKPGbA?dAf@lEFnCd@|EDx@AxBZnE@nAL`C@f@An@LhDPpA|Ad@?VAL_@\\IPo@JkAf@k@d@g@P]^[FMFOPUx@G\\Lx@N^ThBRv@B\\Pv@VnBHZd@^h@Sd@?^XNP^bANTF?@C@QIwC@_BGcAHwC?wBDaCm@{Ba@q@[}AWiFq@{FAcADkBNm@MsBBaAGw@M_AWkD@kAIoAS_BCqA@oBMuE?}BBq@BOHKLCZxBPtC?`@AZ]\\S`@CNC~@D~@?h@Jx@RfAHdA?jBLfADnARdBVvIVzE?hAGDEEMw@i@eDCiABaBL]BAJPV`GLrAB`DFpBP|@R`@C@IQQu@SwBQuASkAKoAQmAEoAFaBDYHKH^?VJp@ZhF@fAFl@@h@?vBJbAHXJRNDRCTYPGDRCLGH]XGZYNoAX_@Nk@b@q@n@SLc@HQf@Oz@Ln@L`@\\~APvA\\dBRlAFVN^DFNDTGTKZ?n@b@DHPr@NZFBLMAm@I_A@sBEuBDqAAiAHiDEmAe@yB_@q@W_BKyBIiAWeBYcDAq@BoADs@H]EcEMo@_@_DK{AEkBI_AM_AGiAAqAB_AGw@IgCF_AEcAFq@PSDBLRFf@RbAPbC@t@CTIPYVGJI\\EZ@`BN|ALn@F|@@lA\\xDPrAFjA@vDJdDR`DDrCDXJxBJz@Vj@ZD^e@HHD^Ur@CD[Na@Bs@\\mBx@k@\\k@P[n@Gl@?n@r@nCRfBZ~AFn@ZlALLD?^GXOPAHBVRTZJ^Tl@HBJECMA{AD{BAcAHmCBmCSgC?w@Gi@Mg@Cu@h@c@BF?PGNIFYLQBYLc@LyCfBe@NGNWp@Cb@@^h@zCJv@@R",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [59.39, 24.65],
    "end_latlng": [59.39, 24.65],
    "average_speed": 2.979,
    "max_speed": 7.517,
    "average_temp": 20,
    "has_heartrate": true,
    "average_heartrate": 165.6,
    "max_heartrate": 186.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 48.2,
    "elev_low": 38.2,
    "upload_id": 14196163414,
    "upload_id_str": "14196163414",
    "external_id": "garmin_ping_400927843395",
    "from_accepted_tag": false,
    "pr_count": 6,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Lunch Swim",
    "distance": 1200.0,
    "moving_time": 1221,
    "elapsed_time": 3172,
    "total_elevation_gain": 0,
    "type": "Swim",
    "sport_type": "Swim",
    "id": 13323464727,
    "start_date": "2025-01-11T10:17:29Z",
    "start_date_local": "2025-01-11T12:17:29Z",
    "timezone": "(GMT+02:00) Africa/Blantyre",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 2,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {"id": "a13323464727", "summary_polyline": "", "resource_state": 2},
    "trainer": true,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [],
    "end_latlng": [],
    "average_speed": 0.983,
    "max_speed": 10.0,
    "has_heartrate": true,
    "average_heartrate": 145.2,
    "max_heartrate": 184.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 0.0,
    "elev_low": 0.0,
    "upload_id": 14210153395,
    "upload_id_str": "14210153395",
    "external_id": "garmin_ping_401386329367",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Afternoon Workout",
    "distance": 0.0,
    "moving_time": 4174,
    "elapsed_time": 4174,
    "total_elevation_gain": 0,
    "type": "Workout",
    "sport_type": "Workout",
    "id": 13334070430,
    "start_date": "2025-01-12T11:54:28Z",
    "start_date_local": "2025-01-12T13:54:28Z",
    "timezone": "(GMT+02:00) Africa/Blantyre",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 2,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {"id": "a13334070430", "summary_polyline": "", "resource_state": 2},
    "trainer": true,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [],
    "end_latlng": [],
    "average_speed": 0.0,
    "max_speed": 0.0,
    "average_temp": 14,
    "has_heartrate": true,
    "average_heartrate": 108.6,
    "max_heartrate": 155.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 0.0,
    "elev_low": 0.0,
    "upload_id": 14221554124,
    "upload_id_str": "14221554124",
    "external_id": "garmin_ping_401686867971",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Morning Swim",
    "distance": 3600.0,
    "moving_time": 3416,
    "elapsed_time": 3460,
    "total_elevation_gain": 0,
    "type": "Swim",
    "sport_type": "Swim",
    "id": 13358921756,
    "start_date": "2025-01-15T05:52:40Z",
    "start_date_local": "2025-01-15T07:52:40Z",
    "timezone": "(GMT+02:00) Africa/Blantyre",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 6,
    "comment_count": 2,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {"id": "a13358921756", "summary_polyline": "", "resource_state": 2},
    "trainer": true,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [],
    "end_latlng": [],
    "average_speed": 1.054,
    "max_speed": 5.56,
    "has_heartrate": true,
    "average_heartrate": 161.5,
    "max_heartrate": 208.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 0.0,
    "elev_low": 0.0,
    "upload_id": 14248226367,
    "upload_id_str": "14248226367",
    "external_id": "garmin_ping_402478770149",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Evening Walk",
    "distance": 3704.1,
    "moving_time": 3656,
    "elapsed_time": 4129,
    "total_elevation_gain": 23.0,
    "type": "Walk",
    "sport_type": "Walk",
    "id": 13380919542,
    "start_date": "2025-01-17T17:16:43Z",
    "start_date_local": "2025-01-17T19:16:43Z",
    "timezone": "(GMT+02:00) Europe/Tallinn",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 5,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a13380919542",
      "summary_polyline":
          "}ayiJobwsCUAi@m@Qa@COBGV`@HVLLt@`B\\l@HHZp@JL?RIp@]pBI|@E~BPdCHrC?dAHlA?`@N`BDjAHp@?TDXAZFj@?f@EVA`@K`@?dAZjAFF\\z@ApBAT@lAFbAFV?LJ\\Hf@JDNCTKHOVSLGZEp@^bAKfAUl@\\j@bAH@hAn@j@t@DL^n@f@bAJBNTd@pAHPVXJRX~@Tf@D@Z~A@XXlARTVPXG@JXTD?n@VPDJANFRCDFJIVIHINEH@FCV@^GT?LBJFRBPER?LA\\F?BLLNBNCHKAm@L[Lg@BE@@CS?MJOFGb@ODBHAP[D?@AJe@Ze@Jo@NQJUBMFsCb@sE?YCS?s@GaCEkAEe@Bc@HO@SAi@KcAAi@?_@DUC}AL_BCo@NmAH_DDg@\\}@Hu@Rm@\\{AEQQEQ@USa@W}@aAI?IMOIOKMAGIa@SOOa@[KECIa@S_@a@KGSEo@i@UOOAq@k@YA[]eAy@i@i@QMQCy@u@OICAUBSUUM_@_@MDKCG@s@YWEQ@M`BCFGD_Ac@SAi@Q?@a@KUMkAa@]OWCKEUG[YQASMOYC?QKy@YKKe@w@SMIQOIIQm@u@KNEPA`AIlAIfAGb@s@fDMNC?IEI@EGEOKOBEGIq@kAO_@C]FODi@@U@A",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [59.44, 24.37],
    "end_latlng": [59.44, 24.37],
    "average_speed": 1.013,
    "max_speed": 1.989,
    "average_cadence": 49.4,
    "average_temp": 23,
    "has_heartrate": true,
    "average_heartrate": 100.4,
    "max_heartrate": 114.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 29.6,
    "elev_low": 12.2,
    "upload_id": 14271879256,
    "upload_id_str": "14271879256",
    "external_id": "garmin_ping_403168461449",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Afternoon Walk",
    "distance": 3938.4,
    "moving_time": 3756,
    "elapsed_time": 4283,
    "total_elevation_gain": 21.0,
    "type": "Walk",
    "sport_type": "Walk",
    "id": 13387851211,
    "start_date": "2025-01-18T13:02:27Z",
    "start_date_local": "2025-01-18T15:02:27Z",
    "timezone": "(GMT+02:00) Europe/Tallinn",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 6,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a13387851211",
      "summary_polyline":
          "gbyiJqbwsCAR@IA@Pd@jAlBDJAZLNANg@dCKx@AdCBJJ~A@`@JtA@b@ARLbC@l@X`EDbCDv@ATUhAEj@B^ZbAf@`A@TFT?jBGjADz@XjBZHLAd@g@TQD?BGLEPJVVXJOAGDtBe@h@BBAJDd@h@JRl@`@VJZZTZVf@NHp@bALFl@xAr@fAXr@Hj@Rb@h@hBF^AHNp@NTf@V@BCbABn@Cp@OlAc@`Ao@pA[dAG`@GnAIf@K\\QbB@`AKd@AZFlADLHHBJVNp@ELETQP?JJHLPj@FJb@H^LFHlAj@VB|BvA`Ab@j@\\THL?No@@S?}@?c@BIA_ABE@yAGqED}AAQAkAFWAkAF_A@cAI{DBYCi@CAAD_@GM?SDOAMBEIEAEBQCY?A@]GWFU@EBS@SHIEI?CCKJKAICO?SGa@OSMQGUOAOQ@SCM@IEOYU}@?_@Ik@w@eBU_Ag@eAOMm@kAOc@CCE@g@}@O_@MQQO[]S@UQMOYm@c@c@QMKAKDW@u@?q@PUKSSQEiA~@OTQ?QMK]?OISKi@Gg@AgARmDOm@Wa@a@mAGs@?QXaBB]Ko@CoAMoA@QKo@BWKy@EkAEyFOkEB}@NiBFi@TgA@_@GEGICQGG?GWKGGWk@KOSk@?K",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [59.44, 24.37],
    "end_latlng": [59.44, 24.37],
    "average_speed": 1.049,
    "max_speed": 2.3,
    "average_cadence": 48.5,
    "average_temp": 22,
    "has_heartrate": true,
    "average_heartrate": 95.1,
    "max_heartrate": 115.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 25.2,
    "elev_low": 6.2,
    "upload_id": 14279389051,
    "upload_id_str": "14279389051",
    "external_id": "garmin_ping_403392435713",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Night Run",
    "distance": 8070.6,
    "moving_time": 3028,
    "elapsed_time": 3079,
    "total_elevation_gain": 19.0,
    "type": "Run",
    "sport_type": "Run",
    "workout_type": null,
    "id": 13391280681,
    "start_date": "2025-01-18T20:25:42Z",
    "start_date_local": "2025-01-18T22:25:42Z",
    "timezone": "(GMT+02:00) Europe/Tallinn",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 8,
    "comment_count": 0,
    "athlete_count": 1,
    "photo_count": 0,
    "map": {
      "id": "a13391280681",
      "summary_polyline":
          "}w}iJayrvCAdAFpBBlBAb@MXC@w@PqALENAjAD`AJtGLnDDnDvAxFDBJLj@J^Jn@Fx@P^^n@v@@LIhAFj@fEnKp@vAvAlDZz@f@x@zApDZpAr@|Bf@bAb@nAp@bBb@nAnAjEZlBx@lG\\rBtA`KP~@L|@HbAI|AJt@JZJv@Ex@YbB?^Lj@Xt@\\r@p@lAlArChAzBh@hAnA`ANd@\\hBz@`Bp@nA~@dATNb@`@HDvBrB|BvAfAz@z@~@fAzAlC~BbBdAbBx@pAv@z@`@b@P|Ax@hAx@rBlANLl@^f@Vb@d@f@^|BhCj@fAj@z@z@|Aj@z@tChFbDpF`ArBdAhBzBnGXr@n@vAnEjLz@lBFH^X@ECI{@oBQ_A_@mAi@eDUu@w@uA_@g@c@w@oAkB]o@w@eBKEYWy@}AYq@k@}@_CiEcAaBaAmB}GeLeDcDqDaCu@g@gIqEmAo@sBqAsBcBICcBsAs@u@W_@i@g@[Sa@MSQgHkG_@c@cAsBoA{BwAaDqB}Du@_B[}@{AiDOcA?KFq@P}@DaAKq@Ss@@iAF}@YyAAWe@uCg@oCScB_@_Cq@oFk@_DCQUgAmAuDmAgC_AcCg@eAu@{CMQo@}Ao@wAi@{A_@y@y@cCiBoE}AaEa@q@Oq@Hs@?o@US]MOOmBu@sAa@W[Ms@q@gCOgAEcDEeAGiFGcB?u@G_A@qA@E",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": null,
    "start_latlng": [59.47, 24.84],
    "end_latlng": [59.47, 24.84],
    "average_speed": 2.665,
    "max_speed": 3.8,
    "average_cadence": 77.0,
    "average_temp": 16,
    "has_heartrate": true,
    "average_heartrate": 178.0,
    "max_heartrate": 187.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 10.8,
    "elev_low": -1.0,
    "upload_id": 14283086269,
    "upload_id_str": "14283086269",
    "external_id": "garmin_ping_403480525550",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  },
  {
    "resource_state": 2,
    "athlete": {"id": 41428532, "resource_state": 1},
    "name": "Night Ride",
    "distance": 6233.5,
    "moving_time": 1915,
    "elapsed_time": 2045,
    "total_elevation_gain": 14.0,
    "type": "Ride",
    "sport_type": "Ride",
    "workout_type": null,
    "id": 13400878693,
    "start_date": "2025-01-19T20:41:36Z",
    "start_date_local": "2025-01-19T22:41:36Z",
    "timezone": "(GMT+02:00) Europe/Tallinn",
    "utc_offset": 7200.0,
    "location_city": null,
    "location_state": null,
    "location_country": null,
    "achievement_count": 0,
    "kudos_count": 4,
    "comment_count": 0,
    "athlete_count": 2,
    "photo_count": 0,
    "map": {
      "id": "a13400878693",
      "summary_polyline":
          "k}jiJkrkuCgA_CiAvAwApAsEhFYNe@A_@Me@WwAsFS_AUu@w@_Dw@oCI@]n@y@nAoArAYd@u@z@EFG@m@h@_@Ji@]q@OUOcAWOM_A][Ie@Yc@MgHsCg@Mk@Uo@Mi@_@m@SsBeAiA_@eCiAmA]sAg@SfGQdDAdA]hJOzB?b@Kz@IhBAx@Ed@QvESjCQjA\\cGXcIPwAFmAHw@DoAAgCFoAXaEHgDVcFFmFN_DRuG^qIPaFDo@\\{K`AoULwFTeODaJGmJEqCi@kO@y@NOPALBBDd@bCDzABN\\BZC^SDFvCvN~AjJ?b@F^RTTz@ZpAx@dEJpBc@vCk@dGB|@Vt@F^fBlG|AlGzFjThBzG`@pAl@lCfCrIlAbFJp@dB~FXx@n@nC^nAx@dDt@nBf@hCVr@ZZ`A^D?JE`@_@tBkCt@m@dAoAbAw@l@}@LDHN~@pB",
      "resource_state": 2
    },
    "trainer": false,
    "commute": false,
    "manual": false,
    "private": false,
    "visibility": "followers_only",
    "flagged": false,
    "gear_id": "b9410632",
    "start_latlng": [59.37, 24.64],
    "end_latlng": [59.37, 24.64],
    "average_speed": 3.255,
    "max_speed": 4.624,
    "average_temp": 15,
    "average_watts": 31.9,
    "device_watts": false,
    "kilojoules": 61.0,
    "has_heartrate": true,
    "average_heartrate": 103.1,
    "max_heartrate": 117.0,
    "heartrate_opt_out": false,
    "display_hide_heartrate_option": true,
    "elev_high": 60.4,
    "elev_low": 52.2,
    "upload_id": 14293453414,
    "upload_id_str": "14293453414",
    "external_id": "garmin_ping_403762998528",
    "from_accepted_tag": false,
    "pr_count": 0,
    "total_photo_count": 0,
    "has_kudoed": false
  }
];
